open-rmf/rmf_simulation

rmf_building_sim_common/CMakeLists.txt
rmf_building_sim_common/QUALITY_DECLARATION.md
rmf_building_sim_common/include/rmf_building_sim_common/slotcar_common.hpp
rmf_building_sim_common/package.xml
rmf_building_sim_common/src/slotcar_common.cpp
rmf_building_sim_gazebo_plugins/CMakeLists.txt
rmf_building_sim_ignition_plugins/CMakeLists.txt
rmf_robot_sim_common/CMakeLists.txt
rmf_robot_sim_common/include/rmf_robot_sim_common/readonly_common.hpp
rmf_robot_sim_common/package.xml
rmf_robot_sim_common/src/readonly_common.cpp
rmf_robot_sim_gazebo_plugins/CMakeLists.txt
rmf_robot_sim_gazebo_plugins/package.xml
rmf_robot_sim_gazebo_plugins/src/readonly.cpp
rmf_robot_sim_ignition_plugins/CMakeLists.txt
rmf_robot_sim_ignition_plugins/package.xml
rmf_robot_sim_ignition_plugins/src/readonly.cpp

Minor refactoring to account for recent refactoring: https://github.com/open-rmf/rmf_traffic_editor/pull/308
Signed-off-by: Boon Han <charayaphan.nakorn.boon.han@gmail.com>

account for renaming from building_map_msgs to rmf_building_map_msgs

---

.github/workflows/build.yaml
.github/workflows/style.yaml
rmf_building_sim_common/include/rmf_building_sim_common/utils.hpp
rmf_robot_sim_common/src/slotcar_common.cpp
rmf_robot_sim_gazebo_plugins/src/slotcar.cpp
rmf_robot_sim_ignition_plugins/src/slotcar.cpp

Added Github workflows for building and code style following the rmf standards.
Inspired from the one in `rmf_demos` and `rmf_traffic_editor`.
Actions are both a nice to have and required by our quality declaration in #1

Add build and style actions

---

.github/workflows/build.yaml
.github/workflows/tsan.yaml
codecov.yml
rmf_building_sim_common/include/rmf_building_sim_common/crowd_simulator_common.hpp
rmf_robot_sim_common/src/ingestor_common.cpp

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
* Added coverage workflow, `coverage-gcc`
* Added thread sanitization workflow, `tsan`
* Using `clang`, `Debug` build and `tsan` colcon mixin.
* Fixed errors that arise when compiling with clang.

Start using ros-tooling for build and test workflow, added coverage, tsan

---

rmf_building_sim_common/QUALITY_DECLARATION.md
rmf_building_sim_common/package.xml
rmf_building_sim_gazebo_plugins/QUALITY_DECLARATION.md
rmf_building_sim_gazebo_plugins/package.xml
rmf_building_sim_ignition_plugins/QUALITY_DECLARATION.md
rmf_building_sim_ignition_plugins/package.xml

Fine tuning some dependencies and adding missing ones to quality declarations.
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

fixing dependencies and quality declaration

---

rmf_building_sim_common/include/rmf_building_sim_common/crowd_simulator_common.hpp
rmf_building_sim_gazebo_plugins/src/crowd_simulator.cpp

Tried building `rmf` with `galactic` and ran into build errors with packages in this repo. I think some of these changes were missed in https://github.com/open-rmf/rmf_simulation/pull/23
Fix https://github.com/open-rmf/rmf/issues/60

Changes for galactic

---

rmf_robot_sim_gazebo_plugins/package.xml

Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

fix typo on gazebo_dev dependency

---

rmf_building_sim_ignition_plugins/src/crowd_simulator.cpp
rmf_building_sim_ignition_plugins/src/door.cpp

Just addressing `RCLCPP_INFO` and `RCLCPP_ERROR` changes and the deprecated `rclcpp::is_initialized()`
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

updating for galactic and rolling compatibility

---

.github/workflows/asan.yaml
.github/workflows/build.yaml
.github/workflows/tsan.yaml

CI is getting caught up with finding and linking rosidl generated packages. The solution I have found is updating ros-setup version and switching to clang + lld.

Fix existing CI

---

.github/workflows/build.yaml

Signed-off-by: Esteban Martinena <orensbruli@gmail.com>
Modified build.yaml workflow to use reusable workflow.

[CI] Reusable CI

---

.github/workflows/asan.yaml
.github/workflows/style.yaml

Signed-off-by: Esteban Martinena <orensbruli@gmail.com>

[CI] Removed push event from workflows

---

.github/workflows/asan.yaml

Signed-off-by: Esteban Martinena <orensbruli@gmail.com>

[CI] Reusable asan workflow

---

.github/workflows/asan.yaml

Address sanitizer uses `foxy`, however, foxy is not supported anymore on main.
Switch to asan action to humble

Change asan to use humble

---

README.md

This PR adds a package description to the top level readme, including a high level overview of the repository organization and details about the supported Gazebo versions and the update schedule.

Update root level readme

---

.github/workflows/build.yaml
rmf_building_sim_gz_plugins/src/door.cpp

Backport joint position reset fix to humble

---

.github/workflows/asan.yaml
.github/workflows/build.yaml
.github/workflows/style.yaml
.github/workflows/tsan.yaml
rmf_building_sim_gz_plugins/src/door.cpp

Backport of joint position reset fix to iron

---

rmf_building_sim_common/include/rmf_building_sim_common/utils.hpp
rmf_building_sim_common/src/utils.cpp
rmf_building_sim_gz_classic_plugins/src/door.cpp
rmf_building_sim_gz_classic_plugins/src/lift.cpp
rmf_building_sim_gz_plugins/src/door.cpp
rmf_building_sim_gz_plugins/src/lift.cpp
rmf_robot_sim_common/include/rmf_robot_sim_common/utils.hpp
rmf_robot_sim_common/src/utils.cpp
rmf_robot_sim_gz_classic_plugins/src/slotcar.cpp
rmf_robot_sim_gz_plugins/src/slotcar.cpp

Backporting the fix for sanitizing node names to iron branch

Backport #110 to iron

---

rmf_building_sim_common/src/door_common.cpp
rmf_building_sim_common/src/lift_common.cpp
rmf_building_sim_gz_classic_plugins/src/toggle_floors.cpp
rmf_robot_sim_common/src/dispenser_common.cpp
rmf_robot_sim_common/src/ingestor_common.cpp

Thanks to @luca-della-vedova for pointing out that using the system default qos might not be appropriate as that depends on the RMW implementation, particularly, for cyclone, it defaults to history depth 1, making it very likely for messages to be silently discarded.
This series of PRs explicitly set a history depth of 10 to all topics and services that does not already set the history depth, those that already set the history depth are untouched. In total 78 instances across rmf codebases are modified, I tested this briefly, so far I haven't encountered any problems yet.
@aaronchongth This might fix some of the "unexplained" issues.

Explicitly specify all qos depth

---

.github/workflows/asan.yaml
.github/workflows/build.yaml
.github/workflows/style.yaml
.github/workflows/tsan.yaml
rmf_building_sim_gz_plugins/src/door.cpp
rmf_building_sim_gz_plugins/src/lift.cpp
rmf_building_sim_gz_plugins/src/toggle_floors/toggle_floors.cpp
rmf_robot_sim_common/src/slotcar_common.cpp
rmf_robot_sim_gz_plugins/src/LightTuning/LightTuning.cpp
rmf_robot_sim_gz_plugins/src/TeleportDispenser.cpp
rmf_robot_sim_gz_plugins/src/TeleportIngestor.cpp

Port and cleanup outdated actions, apply `ament_uncrustify` to fix style issues

Port outdated actions to Noble

---

rmf_building_sim_gz_plugins/CHANGELOG.rst
rmf_building_sim_gz_plugins/package.xml
rmf_robot_sim_common/CHANGELOG.rst
rmf_robot_sim_common/package.xml
rmf_robot_sim_gz_plugins/CHANGELOG.rst
rmf_robot_sim_gz_plugins/package.xml

Rerelease to fix #137, will bloom afterwards

Update changelog and bump to 2.4.1

---

rmf_building_sim_gz_plugins/CHANGELOG.rst
rmf_building_sim_gz_plugins/package.xml
rmf_robot_sim_common/CHANGELOG.rst
rmf_robot_sim_common/package.xml
rmf_robot_sim_gz_plugins/CHANGELOG.rst
rmf_robot_sim_gz_plugins/package.xml

Will tag main once this is merged.

Bump main to 2.5.0
